name: ZoomacIt
options:
  bundleIdPrefix: com.x07jp27
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.40"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    ENABLE_HARDENED_RUNTIME: true

targets:
  ZoomacIt:
    type: application
    platform: macOS
    sources:
      - path: ZoomacIt
    settings:
      base:
        INFOPLIST_FILE: ZoomacIt/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: ZoomacIt
        COMBINE_HIDPI_IMAGES: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: T74PC5F324

  ZoomacItTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ZoomacItTests
    dependencies:
      - target: ZoomacIt
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ZoomacIt.app/Contents/MacOS/ZoomacIt"
        BUNDLE_LOADER: "$(TEST_HOST)"
